name: Continous Integration

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build on Continous Integration
      run: go build -v ./...

    - name: Test on Continous Integration
      run: go test -v ./...
